# scripts/android/env.sh — source me from every Android script and shell.
# Single source of truth for the Android toolchain on this machine; never put
# machine-specific paths anywhere else (android/ is regenerated by prebuild,
# app.json must stay portable for EAS).
#
# JDK: Gradle 9.3.1 (SDK 57 / RN 0.86) supports Java 17-25, but AGP 8.12 and
# Kotlin 2.1.20 are tested on 17/21 only. The system Temurin JDK 25 fails
# inside Gradle on the SDK-54-era toolchain and is off the tested path on 57 —
# pin the Android Studio JBR (21). EAS builds use JDK 17 (ubuntu-26.04-jdk-17-
# ndk-r27b-sdk-57); override with DEENDAWN_JDK if local/EAS parity matters.
export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
export JAVA_HOME="${DEENDAWN_JDK:-/Applications/Android Studio.app/Contents/jbr/Contents/Home}"
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/build-tools/36.0.0:$PATH"
export APP_ID=com.khavion.deendawn
