const { withDangerousMod, withXcodeProject, IOSConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const FILE_NAME = 'AppearanceHardening.m';

const FILE_CONTENTS = `// Generated by plugins/withAppearanceHardening.js — do not edit by hand.
//
// RN 0.86 recomputes the JS color scheme from whichever RN surface posted the
// trait-change notification. A second window in a different trait environment
// (the dev-only LogBox window is a confirmed candidate) makes
// useColorScheme() oscillate between light and dark while the OS appearance
// never changes, and JS content then disagrees with natively drawn chrome.
// This public RN switch makes RCTAppearance always derive the scheme from the
// KEY window's traits instead of the poster's.
// Evidence + sources: docs/reports/darkmode-oscillation-research.md.
#import <React/RCTAppearance.h>

@interface AppearanceHardening : NSObject
@end

@implementation AppearanceHardening
+ (void)load {
  RCTUseKeyWindowForSystemStyle(YES);
}
@end
`;

/**
 * Writes AppearanceHardening.m into the iOS project and registers it with the
 * app target so its +load runs at startup, before any RN surface exists.
 */
function withAppearanceHardening(config) {
  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
      const dest = path.join(cfg.modRequest.platformProjectRoot, projectName, FILE_NAME);
      fs.writeFileSync(dest, FILE_CONTENTS);
      return cfg;
    },
  ]);

  config = withXcodeProject(config, (cfg) => {
    const projectName = IOSConfig.XcodeUtils.getProjectName(cfg.modRequest.projectRoot);
    const relativePath = `${projectName}/${FILE_NAME}`;
    if (!cfg.modResults.hasFile(relativePath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: relativePath,
        groupName: projectName,
        project: cfg.modResults,
      });
    }
    return cfg;
  });

  return config;
}

module.exports = withAppearanceHardening;
