/**
 * Bundled offline city list for the manual-location fallback (CLAUDE.md
 * privacy invariant: manual city entry must always work with no network).
 * Coordinates are city-center approximations (~0.01 deg, adequate for prayer
 * times which shift <1 min over that distance). Curated set weighted toward
 * large metros and major Muslim-population centers; not exhaustive — users
 * can be anywhere between entries, GPS remains the precise path.
 */
export interface City {
  id: string;
  name: string;
  country: string;
  latitude: number;
  longitude: number;
}

export const CITIES: City[] = [
  // North America
  {
    id: 'houston-us',
    name: 'Houston',
    country: 'United States',
    latitude: 29.76,
    longitude: -95.37,
  },
  { id: 'nyc-us', name: 'New York', country: 'United States', latitude: 40.71, longitude: -74.01 },
  {
    id: 'chicago-us',
    name: 'Chicago',
    country: 'United States',
    latitude: 41.88,
    longitude: -87.63,
  },
  {
    id: 'la-us',
    name: 'Los Angeles',
    country: 'United States',
    latitude: 34.05,
    longitude: -118.24,
  },
  { id: 'dallas-us', name: 'Dallas', country: 'United States', latitude: 32.78, longitude: -96.8 },
  {
    id: 'detroit-us',
    name: 'Detroit',
    country: 'United States',
    latitude: 42.33,
    longitude: -83.05,
  },
  {
    id: 'philadelphia-us',
    name: 'Philadelphia',
    country: 'United States',
    latitude: 39.95,
    longitude: -75.17,
  },
  {
    id: 'atlanta-us',
    name: 'Atlanta',
    country: 'United States',
    latitude: 33.75,
    longitude: -84.39,
  },
  { id: 'boston-us', name: 'Boston', country: 'United States', latitude: 42.36, longitude: -71.06 },
  {
    id: 'sf-us',
    name: 'San Francisco',
    country: 'United States',
    latitude: 37.77,
    longitude: -122.42,
  },
  {
    id: 'seattle-us',
    name: 'Seattle',
    country: 'United States',
    latitude: 47.61,
    longitude: -122.33,
  },
  { id: 'miami-us', name: 'Miami', country: 'United States', latitude: 25.76, longitude: -80.19 },
  {
    id: 'minneapolis-us',
    name: 'Minneapolis',
    country: 'United States',
    latitude: 44.98,
    longitude: -93.27,
  },
  {
    id: 'phoenix-us',
    name: 'Phoenix',
    country: 'United States',
    latitude: 33.45,
    longitude: -112.07,
  },
  {
    id: 'denver-us',
    name: 'Denver',
    country: 'United States',
    latitude: 39.74,
    longitude: -104.99,
  },
  {
    id: 'anchorage-us',
    name: 'Anchorage',
    country: 'United States',
    latitude: 61.22,
    longitude: -149.9,
  },
  { id: 'toronto-ca', name: 'Toronto', country: 'Canada', latitude: 43.65, longitude: -79.38 },
  { id: 'montreal-ca', name: 'Montreal', country: 'Canada', latitude: 45.5, longitude: -73.57 },
  { id: 'vancouver-ca', name: 'Vancouver', country: 'Canada', latitude: 49.28, longitude: -123.12 },
  { id: 'calgary-ca', name: 'Calgary', country: 'Canada', latitude: 51.05, longitude: -114.07 },
  { id: 'ottawa-ca', name: 'Ottawa', country: 'Canada', latitude: 45.42, longitude: -75.7 },
  { id: 'edmonton-ca', name: 'Edmonton', country: 'Canada', latitude: 53.55, longitude: -113.49 },
  {
    id: 'mexico-city-mx',
    name: 'Mexico City',
    country: 'Mexico',
    latitude: 19.43,
    longitude: -99.13,
  },

  // Europe
  { id: 'london-gb', name: 'London', country: 'United Kingdom', latitude: 51.51, longitude: -0.13 },
  {
    id: 'birmingham-gb',
    name: 'Birmingham',
    country: 'United Kingdom',
    latitude: 52.48,
    longitude: -1.9,
  },
  {
    id: 'manchester-gb',
    name: 'Manchester',
    country: 'United Kingdom',
    latitude: 53.48,
    longitude: -2.24,
  },
  {
    id: 'bradford-gb',
    name: 'Bradford',
    country: 'United Kingdom',
    latitude: 53.8,
    longitude: -1.75,
  },
  {
    id: 'glasgow-gb',
    name: 'Glasgow',
    country: 'United Kingdom',
    latitude: 55.86,
    longitude: -4.25,
  },
  { id: 'paris-fr', name: 'Paris', country: 'France', latitude: 48.86, longitude: 2.35 },
  { id: 'marseille-fr', name: 'Marseille', country: 'France', latitude: 43.3, longitude: 5.37 },
  { id: 'lyon-fr', name: 'Lyon', country: 'France', latitude: 45.76, longitude: 4.84 },
  { id: 'berlin-de', name: 'Berlin', country: 'Germany', latitude: 52.52, longitude: 13.41 },
  { id: 'hamburg-de', name: 'Hamburg', country: 'Germany', latitude: 53.55, longitude: 9.99 },
  { id: 'cologne-de', name: 'Cologne', country: 'Germany', latitude: 50.94, longitude: 6.96 },
  { id: 'frankfurt-de', name: 'Frankfurt', country: 'Germany', latitude: 50.11, longitude: 8.68 },
  { id: 'munich-de', name: 'Munich', country: 'Germany', latitude: 48.14, longitude: 11.58 },
  {
    id: 'amsterdam-nl',
    name: 'Amsterdam',
    country: 'Netherlands',
    latitude: 52.37,
    longitude: 4.9,
  },
  {
    id: 'rotterdam-nl',
    name: 'Rotterdam',
    country: 'Netherlands',
    latitude: 51.92,
    longitude: 4.48,
  },
  { id: 'brussels-be', name: 'Brussels', country: 'Belgium', latitude: 50.85, longitude: 4.35 },
  { id: 'stockholm-se', name: 'Stockholm', country: 'Sweden', latitude: 59.33, longitude: 18.07 },
  { id: 'gothenburg-se', name: 'Gothenburg', country: 'Sweden', latitude: 57.71, longitude: 11.97 },
  { id: 'malmo-se', name: 'Malmö', country: 'Sweden', latitude: 55.6, longitude: 13.0 },
  { id: 'oslo-no', name: 'Oslo', country: 'Norway', latitude: 59.91, longitude: 10.75 },
  {
    id: 'copenhagen-dk',
    name: 'Copenhagen',
    country: 'Denmark',
    latitude: 55.68,
    longitude: 12.57,
  },
  { id: 'madrid-es', name: 'Madrid', country: 'Spain', latitude: 40.42, longitude: -3.7 },
  { id: 'barcelona-es', name: 'Barcelona', country: 'Spain', latitude: 41.39, longitude: 2.17 },
  { id: 'rome-it', name: 'Rome', country: 'Italy', latitude: 41.9, longitude: 12.5 },
  { id: 'milan-it', name: 'Milan', country: 'Italy', latitude: 45.46, longitude: 9.19 },
  { id: 'vienna-at', name: 'Vienna', country: 'Austria', latitude: 48.21, longitude: 16.37 },
  { id: 'zurich-ch', name: 'Zurich', country: 'Switzerland', latitude: 47.37, longitude: 8.54 },
  { id: 'moscow-ru', name: 'Moscow', country: 'Russia', latitude: 55.76, longitude: 37.62 },
  {
    id: 'sarajevo-ba',
    name: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    latitude: 43.86,
    longitude: 18.41,
  },
  { id: 'tirana-al', name: 'Tirana', country: 'Albania', latitude: 41.33, longitude: 19.82 },
  { id: 'pristina-xk', name: 'Pristina', country: 'Kosovo', latitude: 42.66, longitude: 21.17 },

  // Middle East & North Africa
  { id: 'makkah-sa', name: 'Makkah', country: 'Saudi Arabia', latitude: 21.42, longitude: 39.83 },
  { id: 'madinah-sa', name: 'Madinah', country: 'Saudi Arabia', latitude: 24.47, longitude: 39.61 },
  { id: 'jeddah-sa', name: 'Jeddah', country: 'Saudi Arabia', latitude: 21.49, longitude: 39.19 },
  { id: 'riyadh-sa', name: 'Riyadh', country: 'Saudi Arabia', latitude: 24.71, longitude: 46.68 },
  {
    id: 'dubai-ae',
    name: 'Dubai',
    country: 'United Arab Emirates',
    latitude: 25.2,
    longitude: 55.27,
  },
  {
    id: 'abu-dhabi-ae',
    name: 'Abu Dhabi',
    country: 'United Arab Emirates',
    latitude: 24.45,
    longitude: 54.38,
  },
  { id: 'doha-qa', name: 'Doha', country: 'Qatar', latitude: 25.29, longitude: 51.53 },
  {
    id: 'kuwait-city-kw',
    name: 'Kuwait City',
    country: 'Kuwait',
    latitude: 29.38,
    longitude: 47.99,
  },
  { id: 'manama-bh', name: 'Manama', country: 'Bahrain', latitude: 26.23, longitude: 50.59 },
  { id: 'muscat-om', name: 'Muscat', country: 'Oman', latitude: 23.59, longitude: 58.41 },
  { id: 'sanaa-ye', name: "Sana'a", country: 'Yemen', latitude: 15.37, longitude: 44.19 },
  { id: 'amman-jo', name: 'Amman', country: 'Jordan', latitude: 31.96, longitude: 35.95 },
  {
    id: 'jerusalem',
    name: 'Jerusalem',
    country: 'Palestine/Israel',
    latitude: 31.78,
    longitude: 35.23,
  },
  { id: 'gaza-ps', name: 'Gaza', country: 'Palestine', latitude: 31.5, longitude: 34.47 },
  { id: 'beirut-lb', name: 'Beirut', country: 'Lebanon', latitude: 33.89, longitude: 35.5 },
  { id: 'damascus-sy', name: 'Damascus', country: 'Syria', latitude: 33.51, longitude: 36.29 },
  { id: 'baghdad-iq', name: 'Baghdad', country: 'Iraq', latitude: 33.31, longitude: 44.37 },
  { id: 'tehran-ir', name: 'Tehran', country: 'Iran', latitude: 35.69, longitude: 51.39 },
  { id: 'istanbul-tr', name: 'Istanbul', country: 'Türkiye', latitude: 41.01, longitude: 28.98 },
  { id: 'ankara-tr', name: 'Ankara', country: 'Türkiye', latitude: 39.93, longitude: 32.86 },
  { id: 'izmir-tr', name: 'Izmir', country: 'Türkiye', latitude: 38.42, longitude: 27.14 },
  { id: 'cairo-eg', name: 'Cairo', country: 'Egypt', latitude: 30.04, longitude: 31.24 },
  { id: 'alexandria-eg', name: 'Alexandria', country: 'Egypt', latitude: 31.2, longitude: 29.92 },
  { id: 'tripoli-ly', name: 'Tripoli', country: 'Libya', latitude: 32.89, longitude: 13.19 },
  { id: 'tunis-tn', name: 'Tunis', country: 'Tunisia', latitude: 36.81, longitude: 10.18 },
  { id: 'algiers-dz', name: 'Algiers', country: 'Algeria', latitude: 36.75, longitude: 3.06 },
  {
    id: 'casablanca-ma',
    name: 'Casablanca',
    country: 'Morocco',
    latitude: 33.57,
    longitude: -7.59,
  },
  { id: 'rabat-ma', name: 'Rabat', country: 'Morocco', latitude: 34.02, longitude: -6.84 },
  { id: 'khartoum-sd', name: 'Khartoum', country: 'Sudan', latitude: 15.5, longitude: 32.56 },

  // South Asia
  { id: 'karachi-pk', name: 'Karachi', country: 'Pakistan', latitude: 24.86, longitude: 67.0 },
  { id: 'lahore-pk', name: 'Lahore', country: 'Pakistan', latitude: 31.55, longitude: 74.34 },
  { id: 'islamabad-pk', name: 'Islamabad', country: 'Pakistan', latitude: 33.68, longitude: 73.05 },
  {
    id: 'faisalabad-pk',
    name: 'Faisalabad',
    country: 'Pakistan',
    latitude: 31.42,
    longitude: 73.08,
  },
  { id: 'peshawar-pk', name: 'Peshawar', country: 'Pakistan', latitude: 34.01, longitude: 71.58 },
  { id: 'multan-pk', name: 'Multan', country: 'Pakistan', latitude: 30.2, longitude: 71.45 },
  { id: 'delhi-in', name: 'Delhi', country: 'India', latitude: 28.61, longitude: 77.21 },
  { id: 'mumbai-in', name: 'Mumbai', country: 'India', latitude: 19.08, longitude: 72.88 },
  { id: 'hyderabad-in', name: 'Hyderabad', country: 'India', latitude: 17.39, longitude: 78.49 },
  { id: 'kolkata-in', name: 'Kolkata', country: 'India', latitude: 22.57, longitude: 88.36 },
  { id: 'chennai-in', name: 'Chennai', country: 'India', latitude: 13.08, longitude: 80.27 },
  { id: 'bangalore-in', name: 'Bengaluru', country: 'India', latitude: 12.97, longitude: 77.59 },
  { id: 'lucknow-in', name: 'Lucknow', country: 'India', latitude: 26.85, longitude: 80.95 },
  { id: 'dhaka-bd', name: 'Dhaka', country: 'Bangladesh', latitude: 23.81, longitude: 90.41 },
  {
    id: 'chittagong-bd',
    name: 'Chattogram',
    country: 'Bangladesh',
    latitude: 22.36,
    longitude: 91.78,
  },
  { id: 'colombo-lk', name: 'Colombo', country: 'Sri Lanka', latitude: 6.93, longitude: 79.85 },
  { id: 'kabul-af', name: 'Kabul', country: 'Afghanistan', latitude: 34.56, longitude: 69.21 },
  { id: 'kathmandu-np', name: 'Kathmandu', country: 'Nepal', latitude: 27.72, longitude: 85.32 },
  { id: 'male-mv', name: 'Malé', country: 'Maldives', latitude: 4.18, longitude: 73.51 },

  // Central & East Asia
  { id: 'tashkent-uz', name: 'Tashkent', country: 'Uzbekistan', latitude: 41.3, longitude: 69.24 },
  { id: 'almaty-kz', name: 'Almaty', country: 'Kazakhstan', latitude: 43.24, longitude: 76.89 },
  { id: 'baku-az', name: 'Baku', country: 'Azerbaijan', latitude: 40.41, longitude: 49.87 },
  { id: 'dushanbe-tj', name: 'Dushanbe', country: 'Tajikistan', latitude: 38.56, longitude: 68.79 },
  { id: 'bishkek-kg', name: 'Bishkek', country: 'Kyrgyzstan', latitude: 42.87, longitude: 74.59 },
  { id: 'beijing-cn', name: 'Beijing', country: 'China', latitude: 39.9, longitude: 116.41 },
  { id: 'urumqi-cn', name: 'Ürümqi', country: 'China', latitude: 43.83, longitude: 87.62 },
  { id: 'tokyo-jp', name: 'Tokyo', country: 'Japan', latitude: 35.68, longitude: 139.69 },
  { id: 'seoul-kr', name: 'Seoul', country: 'South Korea', latitude: 37.57, longitude: 126.98 },

  // Southeast Asia & Oceania
  { id: 'jakarta-id', name: 'Jakarta', country: 'Indonesia', latitude: -6.21, longitude: 106.85 },
  { id: 'surabaya-id', name: 'Surabaya', country: 'Indonesia', latitude: -7.26, longitude: 112.75 },
  { id: 'bandung-id', name: 'Bandung', country: 'Indonesia', latitude: -6.92, longitude: 107.61 },
  { id: 'medan-id', name: 'Medan', country: 'Indonesia', latitude: 3.59, longitude: 98.67 },
  {
    id: 'kuala-lumpur-my',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    latitude: 3.14,
    longitude: 101.69,
  },
  {
    id: 'singapore-sg',
    name: 'Singapore',
    country: 'Singapore',
    latitude: 1.35,
    longitude: 103.82,
  },
  { id: 'bangkok-th', name: 'Bangkok', country: 'Thailand', latitude: 13.76, longitude: 100.5 },
  { id: 'manila-ph', name: 'Manila', country: 'Philippines', latitude: 14.6, longitude: 120.98 },
  {
    id: 'brunei-bn',
    name: 'Bandar Seri Begawan',
    country: 'Brunei',
    latitude: 4.9,
    longitude: 114.94,
  },
  { id: 'sydney-au', name: 'Sydney', country: 'Australia', latitude: -33.87, longitude: 151.21 },
  {
    id: 'melbourne-au',
    name: 'Melbourne',
    country: 'Australia',
    latitude: -37.81,
    longitude: 144.96,
  },
  {
    id: 'auckland-nz',
    name: 'Auckland',
    country: 'New Zealand',
    latitude: -36.85,
    longitude: 174.76,
  },

  // Sub-Saharan Africa
  { id: 'lagos-ng', name: 'Lagos', country: 'Nigeria', latitude: 6.52, longitude: 3.38 },
  { id: 'kano-ng', name: 'Kano', country: 'Nigeria', latitude: 12.0, longitude: 8.52 },
  { id: 'abuja-ng', name: 'Abuja', country: 'Nigeria', latitude: 9.06, longitude: 7.5 },
  { id: 'dakar-sn', name: 'Dakar', country: 'Senegal', latitude: 14.72, longitude: -17.47 },
  { id: 'bamako-ml', name: 'Bamako', country: 'Mali', latitude: 12.64, longitude: -8.0 },
  { id: 'accra-gh', name: 'Accra', country: 'Ghana', latitude: 5.6, longitude: -0.19 },
  {
    id: 'addis-ababa-et',
    name: 'Addis Ababa',
    country: 'Ethiopia',
    latitude: 9.01,
    longitude: 38.75,
  },
  { id: 'mogadishu-so', name: 'Mogadishu', country: 'Somalia', latitude: 2.05, longitude: 45.32 },
  { id: 'nairobi-ke', name: 'Nairobi', country: 'Kenya', latitude: -1.29, longitude: 36.82 },
  {
    id: 'dar-es-salaam-tz',
    name: 'Dar es Salaam',
    country: 'Tanzania',
    latitude: -6.79,
    longitude: 39.21,
  },
  {
    id: 'johannesburg-za',
    name: 'Johannesburg',
    country: 'South Africa',
    latitude: -26.2,
    longitude: 28.05,
  },
  {
    id: 'cape-town-za',
    name: 'Cape Town',
    country: 'South Africa',
    latitude: -33.92,
    longitude: 18.42,
  },

  // South America
  { id: 'sao-paulo-br', name: 'São Paulo', country: 'Brazil', latitude: -23.55, longitude: -46.63 },
  {
    id: 'buenos-aires-ar',
    name: 'Buenos Aires',
    country: 'Argentina',
    latitude: -34.6,
    longitude: -58.38,
  },
];
